[package]
name = "aoc2018"
version = "0.1.0"
authors = ["Alexander J Trelore <alextrelore@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.1.0"
lazy_static = "1.2.0"
arrayvec = "0.4.8"
